package com.example.network

import com.example.models.*
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.MultipartBody
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.*
import java.util.concurrent.TimeUnit

// --- Gemini REST API Request & Response Data Models (Moshi-compatible) ---

data class GeminiRequest(
    val contents: List<GeminiContent>,
    val systemInstruction: GeminiContent? = null,
    val generationConfig: GeminiGenerationConfig? = null
)

data class GeminiContent(
    val parts: List<GeminiPart>,
    val role: String? = null
)

data class GeminiPart(
    val text: String? = null
)

data class GeminiGenerationConfig(
    val temperature: Float? = null,
    val maxOutputTokens: Int? = null
)

data class GeminiResponse(
    val candidates: List<GeminiCandidate>?
)

data class GeminiCandidate(
    val content: GeminiContent?
)


// --- Retrofit Network Interfaces ---

// Existing future vocal analysis API generated by AI Studio.
// We are keeping this for now so the generated project does not break.
interface VocaApiService {

    @Multipart
    @POST("api/v1/vocal/upload")
    suspend fun uploadAudio(
        @Part audio: MultipartBody.Part,
        @Header("Authorization") token: String
    ): AudioUploadResponse

    @GET("api/v1/vocal/performance")
    suspend fun getPerformanceReport(
        @Query("userId") userId: String
    ): UserPerformanceReport

    @GET("api/v1/vocal/recommendations")
    suspend fun getCoachingRecommendations(
        @Query("skillLevel") skillLevel: String
    ): List<CoachingRecommendation>
}


// Live Gemini API Service for Coaching Chat
interface GeminiApiService {

    @POST("v1beta/models/{model}:generateContent")
    suspend fun generateContent(
        @Path("model") model: String,
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}


// --- Retrofit Client Singleton ---

object RetrofitClient {

    /*
     * Cadenza local backend URL.
     *
     * For Android Emulator:
     * Use http://10.0.2.2:8000/
     *
     * For Physical Android Phone:
     * Replace this with your laptop/PC Wi-Fi IP.
     * Example:
     * http://192.168.1.5:8000/
     */
    private const val CADENZA_BASE_URL = "http://10.196.239.136:8000/"

    // Existing mock backend generated by AI Studio.
    // Keeping it untouched for now.
    private const val V_BASE_URL = "https://api.vocaai-coach-mock.com/"

    // Gemini API base URL.
    private const val GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/"


    private val moshi: Moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()


    private val okHttpClient: OkHttpClient by lazy {
        OkHttpClient.Builder()
            .connectTimeout(60, TimeUnit.SECONDS)
            .readTimeout(600, TimeUnit.SECONDS)
            .writeTimeout(600, TimeUnit.SECONDS)
            .build()
    }


    // Service for our real Cadenza FastAPI backend.
    val cadenzaService: CadenzaApiService by lazy {
        Retrofit.Builder()
            .baseUrl(CADENZA_BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(CadenzaApiService::class.java)
    }


    // Service for future startup API generated by AI Studio.
    val vocaService: VocaApiService by lazy {
        Retrofit.Builder()
            .baseUrl(V_BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(VocaApiService::class.java)
    }


    // Service for live AI chat via Google Gemini.
    val geminiService: GeminiApiService by lazy {
        Retrofit.Builder()
            .baseUrl(GEMINI_BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(GeminiApiService::class.java)
    }
}